// Styles
import '@/pages/ui-kit/ui-kit.scss';
import '@/pages/landing-page/landing-page.scss';
import '@/pages/search-room/search-room.scss';
import '@/pages/room-details/room-details.scss';
import '@/pages/registration-page/registration-page.scss';
import '@/pages/signin-page/signin-page.scss';
import '@/pages/page-with-links/page-with-links.scss';

// color-block
import '@/common.blocks/color-block/color-block.scss';
import '@/common.blocks/color-block/__color-code/color-block__color-code.scss';
import '@/common.blocks/color-block/__color-name/color-block__color-name.scss';
import '@/common.blocks/color-block/__description/color-block__description.scss';
import '@/common.blocks/color-block/__square/color-block__square.scss';
import '@/common.blocks/color-block/__square/_dark-shade-5/color-block__square_dark-shade-5.scss';
import '@/common.blocks/color-block/__square/_dark-shade-25/color-block__square_dark-shade-25.scss';
import '@/common.blocks/color-block/__square/_dark-shade-50/color-block__square_dark-shade-50.scss';
import '@/common.blocks/color-block/__square/_dark-shade-75/color-block__square_dark-shade-75.scss';
import '@/common.blocks/color-block/__square/_dark-shade-100/color-block__square_dark-shade-100.scss';
import '@/common.blocks/color-block/__square/_green/color-block__square_green.scss';
import '@/common.blocks/color-block/__square/_purple/color-block__square_purple.scss';

// type-block
import '@/common.blocks/type-block/type-block.scss';
import '@/common.blocks/type-block/__tag/type-block__tag.scss';
import '@/common.blocks/type-block/__text/type-block__text.scss';

// text-field
import '@/common.blocks/text-field/__arrow-forward/text-field__arrow-forward.scss';
import '@/common.blocks/text-field/__title/text-field__title.scss';
import '@/common.blocks/text-field/__field/text-field__field.scss';
import '@/common.blocks/text-field/__field/_subscription/text-field__field_subscription.scss';
import '@/common.blocks/text-field/__subscription-btn/text-field__subscription-btn.scss';
import '@/common.blocks/text-field/text-field.scss';

// dropdown
import '@/common.blocks/dropdown/dropdown.scss';
import '@/common.blocks/dropdown/__title/dropdown__title.scss';
import '@/common.blocks/dropdown/__header/dropdown__header.scss';
import '@/common.blocks/dropdown/__header/_all-angles-are-round/dropdown__header_all-angles-are-round.scss';
import '@/common.blocks/dropdown/__header/_top-angles-are-round/dropdown__header_top-angles-are-round.scss';
import '@/common.blocks/dropdown/__header-text/dropdown__header-text.scss';
import '@/common.blocks/dropdown/__expand-more/dropdown__expand-more.scss';
import '@/common.blocks/dropdown/__expand-more/_absolute/dropdown__expand-more_absolute.scss';
import '@/common.blocks/dropdown/__date-section/dropdown__date-section.scss';
import '@/common.blocks/dropdown/__start-date-header/dropdown__start-date-header.scss';
import '@/common.blocks/dropdown/__end-date-header/dropdown__end-date-header.scss';
import '@/common.blocks/dropdown/__date-block/dropdown__date-block.scss';
import '@/common.blocks/dropdown/__drop-menu/dropdown__drop-menu.scss';
import '@/common.blocks/dropdown/__drop-menu/_with-border/dropdown__drop-menu_with-border.scss';
import '@/common.blocks/dropdown/__check/dropdown__check.scss';
import '@/common.blocks/dropdown/__option/dropdown__option.scss';
import '@/common.blocks/dropdown/__quantity-selection/dropdown__quantity-selection.scss';
import '@/common.blocks/dropdown/__quantity-number/dropdown__quantity-number.scss';
import '@/common.blocks/dropdown/__quantity-button/dropdown__quantity-button.scss';
import '@/common.blocks/dropdown/__bottom-buttons-panel/dropdown__bottom-buttons-panel.scss';
import '@/common.blocks/dropdown/__button-clear/dropdown__button-clear.scss';

// expandable-checkbox-list
import '@/common.blocks/expandable-checkbox-list/expandable-checkbox-list.scss';
import '@/common.blocks/expandable-checkbox-list/__check/expandable-checkbox-list__check.scss';
import '@/common.blocks/expandable-checkbox-list/__title-section/expandable-checkbox-list__title-section.scss';
import '@/common.blocks/expandable-checkbox-list/__title/expandable-checkbox-list__title.scss';
import '@/common.blocks/expandable-checkbox-list/__expand-more/expandable-checkbox-list__expand-more.scss';
import '@/common.blocks/expandable-checkbox-list/__hide-list/expandable-checkbox-list__hide-list.scss';

// room-details
import '@/common.blocks/room-details/room-details.scss';
import '@/common.blocks/room-details/__icon/room-details__icon.scss';
import '@/common.blocks/room-details/__text/room-details__text.scss';
import '@/common.blocks/room-details/__title/room-details__title.scss';

// checkbox-button
import '@/common.blocks/checkbox-button/checkbox-button.scss';
import '@/common.blocks/checkbox-button/_rich/checkbox-button_rich.scss';
import '@/common.blocks/checkbox-button/__text/checkbox-button__text.scss';
import '@/common.blocks/checkbox-button/__label/checkbox-button__label.scss';
import '@/common.blocks/checkbox-button/__label/_rich/checkbox-button__label_rich.scss';
import '@/common.blocks/checkbox-button/__checkbox-element/checkbox-button__checkbox-element.scss';

// radio-button
import '@/common.blocks/radio-button/radio-button.scss';
import '@/common.blocks/radio-button/__radio-element/radio-button__radio-element.scss';
import '@/common.blocks/radio-button/__label/radio-button__label.scss';

// toggle
import '@/common.blocks/toggle/__checkbox/toggle__checkbox.scss';
import '@/common.blocks/toggle/__label/toggle__label.scss';

// like-button
import '@/common.blocks/like-button/like-button.scss';
import '@/common.blocks/like-button/_checked/like-button_checked.scss';
import '@/common.blocks/like-button/_unchecked/like-button_unchecked.scss';
import '@/common.blocks/like-button/__heart/like-button__heart.scss';

import '@/common.blocks/rate-button/rate-button.scss';
import '@/common.blocks/rate-button/__star/rate-button__star.scss';

// range-slider
import '@/common.blocks/range-slider/range-slider.scss';
import '@/common.blocks/range-slider/__header-section/range-slider__header-section.scss';
import '@/common.blocks/range-slider/__title/range-slider__title.scss';
import '@/common.blocks/range-slider/__range-label/range-slider__range-label.scss';
import '@/common.blocks/range-slider/__slider/range-slider__slider.scss';
import '@/common.blocks/range-slider/__track/range-slider__track.scss';
import '@/common.blocks/range-slider/__range/range-slider__range.scss';
import '@/common.blocks/range-slider/__thumb/range-slider__thumb.scss';
import '@/common.blocks/range-slider/__thumb/_left/range-slider__thumb_left.scss';
import '@/common.blocks/range-slider/__thumb/_right/range-slider__thumb_right.scss';
import '@/common.blocks/range-slider/__thumb/_left/_hover/range-slider__thumb_left_hover.scss';
import '@/common.blocks/range-slider/__thumb/_right/_hover/range-slider__thumb_right_hover.scss';
import '@/common.blocks/range-slider/__input-range/range-slider__input-range.scss';

// button
import '@/common.blocks/button/button.scss';
import '@/common.blocks/button/_regular/button_regular.scss';
import '@/common.blocks/button/_with-border/button_with-border.scss';
import '@/common.blocks/button/_only-text/button_only-text.scss';
import '@/common.blocks/button/_only-text/_gray/button_only-text_gray.scss';
import '@/common.blocks/button/_with-arrow/button_with-arrow.scss';
import '@/common.blocks/button/__arrow/button__arrow.scss';
import '@/common.blocks/button/_with-vertical-paddings-10/button_with-vertical-paddings-10.scss';
import '@/common.blocks/button/_with-vertical-paddings-8/button_with-vertical-paddings-8.scss';

// pagination
import '@/common.blocks/pagination/pagination.scss';
import '@/common.blocks/pagination/__pages/pagination__pages.scss';
import '@/common.blocks/pagination/__button/pagination__button.scss';
import '@/common.blocks/pagination/__button/_with-number/pagination__button_with-number.scss';
import '@/common.blocks/pagination/__button/_with-arrow/pagination__button_with-arrow.scss';
import '@/common.blocks/pagination/__button/_active-page/pagination__button_active-page.scss';
import '@/common.blocks/pagination/__arrow/pagination__arrow.scss';
import '@/common.blocks/pagination/__signature/pagination__signature.scss';
import '@/common.blocks/pagination/__signature/_with-top-margin/pagination__signature_with-top-margin.scss';
import '@/common.blocks/pagination/__link/pagination__link.scss';

// bullet-list
import '@/common.blocks/bullet-list/__unordered-list/bullet-list__unordered-list.scss';
import '@/common.blocks/bullet-list/__item/bullet-list__item.scss';
import '@/common.blocks/bullet-list/__item/_standard-theme/bullet-list__item_standard-theme.scss';

// guest-review
import '@/common.blocks/guest-review/guest-review.scss';
import '@/common.blocks/guest-review/__guest/guest-review__guest.scss';
import '@/common.blocks/guest-review/__photo/guest-review__photo.scss';
import '@/common.blocks/guest-review/__guest-details/guest-review__guest-details.scss';
import '@/common.blocks/guest-review/__guest-name/guest-review__guest-name.scss';
import '@/common.blocks/guest-review/__rewiew/guest-review__rewiew.scss';
import '@/common.blocks/guest-review/__likes/guest-review__likes.scss';
import '@/common.blocks/guest-review/__rewiew-text/guest-review__rewiew-text.scss';

// calendar
import '@/common.blocks/calendar/calendar.scss';
import '@/common.blocks/calendar/_standart-theme/calendar_standart-theme.scss';
import '@/common.blocks/calendar/__month-selection-section/calendar__month-selection-section.scss';
import '@/common.blocks/calendar/__month-button/calendar__month-button.scss';
import '@/common.blocks/calendar/__month-button/_standart-theme/calendar__month-button_standart-theme.scss';
import '@/common.blocks/calendar/__month-name/calendar__month-name.scss';
import '@/common.blocks/calendar/__month-name/_standart-theme/calendar__month-name_standart-theme.scss';
import '@/common.blocks/calendar/__days-section/calendar__days-section.scss';
import '@/common.blocks/calendar/__names-of-week-days-section/calendar__names-of-week-days-section.scss';
import '@/common.blocks/calendar/__names-of-week-days-section/_standart-theme/calendar__names-of-week-days-section_standart-theme.scss';
import '@/common.blocks/calendar/__week-day/calendar__week-day.scss';
import '@/common.blocks/calendar/__week-section/calendar__week-section.scss';
import '@/common.blocks/calendar/__day/calendar__day.scss';
import '@/common.blocks/calendar/__day/_current/calendar__day_current.scss';
import '@/common.blocks/calendar/__day/_other-month/calendar__day_other-month.scss';
import '@/common.blocks/calendar/__buttons-panel/calendar__buttons-panel.scss';
import '@/common.blocks/calendar/__day/_selectable/calendar__day_selectable.scss';
import '@/common.blocks/calendar/__range-highlight/calendar__range-highlight.scss';
import '@/common.blocks/calendar/__range-highlight/_left-rounded/calendar__range-highlight_left-rounded.scss';
import '@/common.blocks/calendar/__range-highlight/_right-rounded/calendar__range-highlight_right-rounded.scss';
import '@/common.blocks/calendar/__day/_selected/calendar__day_selected.scss';
import '@/common.blocks/calendar/_without-top-border/calendar_without-top-border.scss';

// number-card
import '@/common.blocks/number-card/number-card.scss';
import '@/common.blocks/number-card/__slider-section/number-card__slider-section.scss';
import '@/common.blocks/number-card/__slider-list/number-card__slider-list.scss';
import '@/common.blocks/number-card/__slider-image/number-card__slider-image.scss';
import '@/common.blocks/number-card/__slider-list-item/number-card__slider-list-item.scss';
import '@/common.blocks/number-card/__slider-list-item/_opacity-0/number-card__slider-list-item_opacity-0.scss';
import '@/common.blocks/number-card/__slider-list-item/_opacity-1/number-card__slider-list-item_opacity-1.scss';
import '@/common.blocks/number-card/__arrow-button/number-card__arrow-button.scss';
import '@/common.blocks/number-card/__arrow-button/_prev/number-card__arrow-button_prev.scss';
import '@/common.blocks/number-card/__arrow-button/_next/number-card__arrow-button_next.scss';
import '@/common.blocks/number-card/__dots-section/number-card__dots-section.scss';
import '@/common.blocks/number-card/__dot/number-card__dot.scss';
import '@/common.blocks/number-card/__dot/_unactive/number-card__dot_unactive.scss';
import '@/common.blocks/number-card/__dot/_active/number-card__dot_active.scss';
import '@/common.blocks/number-card/__room-info/number-card__room-info.scss';
import '@/common.blocks/number-card/__number-section/number-card__number-section.scss';
import '@/common.blocks/number-card/__number/number-card__number.scss';
import '@/common.blocks/number-card/__number/_size-19/number-card__number_size-19.scss';
import '@/common.blocks/number-card/__lux/number-card__lux.scss';
import '@/common.blocks/number-card/__room-rate/number-card__room-rate.scss';
import '@/common.blocks/number-card/__accented-text/number-card__accented-text.scss';
import '@/common.blocks/number-card/__separator/number-card__separator.scss';
import '@/common.blocks/number-card/__rating-section/number-card__rating-section.scss';

// search-room-card
import '@/common.blocks/search-room-card/search-room-card.scss';
import '@/common.blocks/search-room-card/__title/search-room-card__title.scss';
import '@/common.blocks/search-room-card/__dropdown/search-room-card__dropdown.scss';
import '@/common.blocks/search-room-card/__title/_margins/search-room-card__title_margins.scss';
import '@/common.blocks/search-room-card/__button/search-room-card__button.scss';

// registration-card
import '@/common.blocks/registration-card/registration-card.scss';
import '@/common.blocks/registration-card/__title/registration-card__title.scss';
import '@/common.blocks/registration-card/__title/_margin-8/registration-card__title_margin-8.scss';
import '@/common.blocks/registration-card/__account-login/registration-card__account-login.scss';
import '@/common.blocks/registration-card/__person/registration-card__person.scss';
import '@/common.blocks/registration-card/__login-details/registration-card__login-details.scss';

// entry-card
import '@/common.blocks/entry-card/entry-card.scss';
import '@/common.blocks/entry-card/__title/entry-card__title.scss';
import '@/common.blocks/entry-card/__new-account-section/entry-card__new-account-section.scss';
import '@/common.blocks/entry-card/__login-section/entry-card__login-section.scss';

// room-rate-card
import '@/common.blocks/room-rate-card/room-rate-card.scss';
import '@/common.blocks/room-rate-card/__room-info/room-rate-card__room-info.scss';
import '@/common.blocks/room-rate-card/__room-number/room-rate-card__room-number.scss';
import '@/common.blocks/room-rate-card/__number/room-rate-card__number.scss';
import '@/common.blocks/room-rate-card/__number/_size-19/room-rate-card__number_size-19.scss';
import '@/common.blocks/room-rate-card/__lux/room-rate-card__lux.scss';
import '@/common.blocks/room-rate-card/__price-per-day/room-rate-card__price-per-day.scss';
import '@/common.blocks/room-rate-card/__cost/room-rate-card__cost.scss';
import '@/common.blocks/room-rate-card/__room-rate-label/room-rate-card__room-rate-label.scss';
import '@/common.blocks/room-rate-card/__drop-guests/room-rate-card__drop-guests.scss';
import '@/common.blocks/room-rate-card/__room-rate-calc/room-rate-card__room-rate-calc.scss';
import '@/common.blocks/room-rate-card/__services/room-rate-card__services.scss';
import '@/common.blocks/room-rate-card/__service-info/room-rate-card__service-info.scss';
import '@/common.blocks/room-rate-card/__service-tooltip/room-rate-card__service-tooltip.scss';
import '@/common.blocks/room-rate-card/__additional-service-tooltip/room-rate-card__additional-service-tooltip.scss';
import '@/common.blocks/room-rate-card/__additional-services/room-rate-card__additional-services.scss';
import '@/common.blocks/room-rate-card/__additional-service-info/room-rate-card__additional-service-info.scss';
import '@/common.blocks/room-rate-card/__services-label/room-rate-card__services-label.scss';
import '@/common.blocks/room-rate-card/__additionals-services-label/room-rate-card__additionals-services-label.scss';
import '@/common.blocks/room-rate-card/__result/room-rate-card__result.scss';
import '@/common.blocks/room-rate-card/__result-dots/room-rate-card__result-dots.scss';
import '@/common.blocks/room-rate-card/__result-label/room-rate-card__result-label.scss';
import '@/common.blocks/room-rate-card/__result-cost/room-rate-card__result-cost.scss';
import '@/common.blocks/room-rate-card/__tooltip/room-rate-card__tooltip.scss';

// header
import '@/common.blocks/header/header.scss';
import '@/common.blocks/header/__menu-check/header__menu-check.scss';
import '@/common.blocks/header/__content/header__content.scss';
import '@/common.blocks/header/__logo/header__logo.scss';
import '@/common.blocks/header/__burger/header__burger.scss';
import '@/common.blocks/header/__burger-image/header__burger-image.scss';

// footer
import '@/common.blocks/footer/footer.scss';
import '@/common.blocks/footer/__info-wrapper/footer__info-wrapper.scss';
import '@/common.blocks/footer/__info/footer__info.scss';
import '@/common.blocks/footer/__info-column/footer__info-column.scss';
import '@/common.blocks/footer/__info-column/_width-260/footer__info-column_width-260.scss';
import '@/common.blocks/footer/__info-item/footer__info-item.scss';
import '@/common.blocks/footer/__info-title/footer__info-title.scss';
import '@/common.blocks/footer/__logo/footer__logo.scss';
import '@/common.blocks/footer/__logo/_hidden/footer__logo_hidden.scss';
import '@/common.blocks/footer/__copyright-wrapper/footer__copyright-wrapper.scss';
import '@/common.blocks/footer/__copyright/footer__copyright.scss';
import '@/common.blocks/footer/__copyright-text/footer__copyright-text.scss';
import '@/common.blocks/footer/__social-link/footer__social-link.scss';

// navbar
import '@/common.blocks/navbar/navbar.scss';
import '@/common.blocks/navbar/__list/navbar__list.scss';
import '@/common.blocks/navbar/__list/_horizontal/navbar__list_horizontal.scss';
import '@/common.blocks/navbar/__list/_vertical/navbar__list_vertical.scss';
import '@/common.blocks/navbar/__list/_vertical-opened/navbar__list_vertical-opened.scss';
import '@/common.blocks/navbar/__item/navbar__item.scss';
import '@/common.blocks/navbar/__item/_with-separator/navbar__item_with-separator.scss';
import '@/common.blocks/navbar/__item/_with-name/navbar__item_with-name.scss';
import '@/common.blocks/navbar/__item/_horizontal/navbar__item_horizontal.scss';
import '@/common.blocks/navbar/__item/_vertical/navbar__item_vertical.scss';
import '@/common.blocks/navbar/__item/_vertical-opened/navbar__item_vertical-opened.scss';
import '@/common.blocks/navbar/__dropdown-title/navbar__dropdown-title.scss';
import '@/common.blocks/navbar/__dropdown-title/_vertical/navbar__dropdown-title_vertical.scss';
import '@/common.blocks/navbar/__hidden-list/navbar__hidden-list.scss';
import '@/common.blocks/navbar/__hidden-list/_vertical/navbar__hidden-list_vertical.scss';
import '@/common.blocks/navbar/__hidden-list/_vertical-opened/navbar__hidden-list_vertical-opened.scss';
import '@/common.blocks/navbar/__hidden-list/_horizontal/navbar__hidden-list_horizontal.scss';
import '@/common.blocks/navbar/__hidden-list-item/navbar__hidden-list-item.scss';
import '@/common.blocks/navbar/__hidden-list-item/_horizontal/navbar__hidden-list-item_horizontal.scss';
import '@/common.blocks/navbar/__hidden-list-item/_vertical/navbar__hidden-list-item_vertical.scss';
import '@/common.blocks/navbar/__button-registration/navbar__button-registration.scss';
import '@/common.blocks/navbar/__button-entry/navbar__button-entry.scss';
import '@/common.blocks/navbar/__separator/navbar__separator.scss';
import '@/common.blocks/navbar/__separator/_vertical/navbar__separator_vertical.scss';

// impressions-diagram
import '@/common.blocks/impressions-diagram/impressions-diagram.scss';
import '@/common.blocks/impressions-diagram/__diagram-section/impressions-diagram__diagram-section.scss';
import '@/common.blocks/impressions-diagram/__votes-counter/impressions-diagram__votes-counter.scss';
import '@/common.blocks/impressions-diagram/__votes-number/impressions-diagram__votes-number.scss';
import '@/common.blocks/impressions-diagram/__votes-text/impressions-diagram__votes-text.scss';
import '@/common.blocks/impressions-diagram/__diagram-legend/impressions-diagram__diagram-legend.scss';
import '@/common.blocks/impressions-diagram/__legend-item/impressions-diagram__legend-item.scss';
import '@/common.blocks/impressions-diagram/__legend-item/_yellow/impressions-diagram__legend-item_yellow.scss';
import '@/common.blocks/impressions-diagram/__legend-item/_green/impressions-diagram__legend-item_green.scss';
import '@/common.blocks/impressions-diagram/__legend-item/_purple/impressions-diagram__legend-item_purple.scss';
import '@/common.blocks/impressions-diagram/__legend-item/_brown/impressions-diagram__legend-item_brown.scss';

// Scripts
import '@/common.blocks/calendar/calendar';
import '@/common.blocks/dropdown/dropdown';
import '@/common.blocks/like-button/like-button';
import '@/common.blocks/navbar/navbar';
import '@/common.blocks/header/header';
import '@/common.blocks/impressions-diagram/impressions-diagram';
import '@/common.blocks/pagination/pagination';
import '@/common.blocks/range-slider/range-slider';
import '@/common.blocks/text-field/text-field';
import '@/common.blocks/number-card/number-card';
import '@/common.blocks/room-rate-card/room-rate-card';
